NDefines.NBuildings.MAX_BUILDING_LEVELS = 50
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NFocus.FOCUS_POINT_DAYS = 3.5
NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 3
NDefines.NProduction.LEND_LEASE_DELIVERY_TOTAL_DAYS = 1
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 25

NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 250
NDefines.NProduction.FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 250
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 250
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 250