NDefines.NProject.RECRUIT_SCIENTIST_COST = {10, 20, 30, 40} -- Defualt {25, 50, 75, 100}
NDefines.NProject.BREAKTHROUGH_DAILY_TECHNOLOGY_GAIN = 14 -- Defualt 12 (+2)
NDefines.NProject.BREAKTHROUGH_DAILY_SCIENTIST_SKILL_GAIN = 7 -- Defualt 5 (+2)
NDefines.NProject.BREAKTHROUGH_DAILY_ROCKET_SITE_GAIN = 3 -- Defualt 3 (+2)
NDefines.NProject.BREAKTHROUGH_DAILY_NUCLEAR_REACTOR_GAIN = 3 -- Defualt 1 (+2)